-- AlterTable
ALTER TABLE `orders` MODIFY `paymentStatus` ENUM('PENDING', 'APPROVED', 'REGECTED', 'REFUNDED', 'CANCELED') NOT NULL,
    MODIFY `deliveryStatus` ENUM('PREPARING', 'TRAVELING', 'DELIVERED', 'CANCELED') NOT NULL;
